version: '3'
services:
  php:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www:cached
      - ../img:/var/www/img:cached
      - ./var/log/nginx:/var/log/nginx:cached
    environment:
      DATABASE_URL: mysql://root:root@db/sandbox
      REDIS_URL: redis://cache:7000
      REDIS_CLUSTER_TYPE: redis
      APP_ENV: dev
      PHOTOS_BASE_PATH: /var/www/img/photos/test
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: sandbox
      MYSQL_DATABASE: sandbox
  cache:
    image: grokzen/redis-cluster # 6 instances, 3 master, 3 slaves
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
