<?php
/**
 * Created by PhpStorm.
 * User: pierre
 * Date: 3/1/19
 * Time: 3:58 PM
 */

declare(strict_types=1);

namespace App\Place;


use App\Place\Place;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

class PlaceRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Place::class);
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    public function persist(Place $place): bool
    {
        $this->getEntityManager()->persist($place);
        $this->getEntityManager()->flush();

        return true;
    }
}
